# Generated by Django 2.0.3 on 2018-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds_setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='floor',
            field=models.IntegerField(),
        ),
    ]
